distributed-text-services/specifications

- userstories.csv
It does not change per se the User Story / Technical Requirement but makes it fit in the terminology.
> Changed Annotate to Update for coherence

- swagger.json
I think this is really a page, not a cursor.
> Switched 'cursor' to 'page'

- distributed-text-services-api.md
the link was leading to a page returing 404
> corrected link

- Collection-Endpoint.md
the sentence about hierarchy of collections was duplicate and I removed the first occurrence
> removed duplicate statement

- Navigation-Endpoint.md
> Making start and end inclusive

- Collection-Endpoint.md
According to Thursday 2018-07-26 discussion.
Up to vote for next Thursday, please review before.
Another modification is required in Navigation but it's on hold for Hydrated PR.
> Added Citation Model to Collection Endpoint

- README.md
Here's my action item promised by this week. An attempt at writing a succinct description of what DTS is.  
Any and all feedback welcome.
> Write up of what DTS is

- Navigation-Endpoint.md
replicating the changes made in the wrong repo
> removed extra commas in examples

- README.md
I made the corrections @PietroLiuzzo suggested, and included a bit more about the reference implementations.
> Add implementation details

- Entry.md
took a stab at updating the entry.md per @PonteIneptique request. Not sure if I covered everything but think it's a little better.
> Balmas patch 2

- Collection-Endpoint.md
- Entry.md
- Navigation-Endpoint.md
Addresses multiple issues that were simple enough and agreed upon.
> Multiple fixes

- Collection-Endpoint.md
- Navigation-Endpoint.md
Tries to improve upon example names and descriptions
> Balmas patch 3

- Collection-Endpoint.md
Caught this mistake implementing a python client.
`@lang` was used instead of `@language`
> Wrong language attribute lang instead of language

- FAQ.md
my action item from the last meeting...
> merged in text from collective google doc

- Navigation-Endpoint.md
This pull request addresses issue #186  by adding the `dts:parent` property to the returned JSON objects from Navigation endpoint requests.
> Added 'dts:parent' property to Navigation endpoint.

- Collections-Endpoint.md
- Cookbook.md
- Navigation-Endpoint.md
- context/1.0.0draft-2.json
This is a fix for #210: it moves the `@context` to a DTS-Specific JSON file and allows for hopefully parsing JSON with OpenAPI or OpenAPI-likes tool.
> Context.json

- Navigation-Endpoint.md
Changing definitions of Navigation `ref`, `start`, and `end` properties/parameters to partially address issue #184
> Changing definitions of Navigation `ref`, `start`, and `end` properties/parameters

- Collection-Endpoint.md
- Navigation-Endpoint.md
Removing URI template and adding `dtsVersion`
> Removing URI template and adding `dtsVersion`

- versions/unstable/README.md
Also adding `totalChildren` to Collection response schema; Changing references to "readable collections" to "resources" in Collection; Clarifying that Collection can return either Collection or Resource objects; Adding missing request for Collection example
> Renaming "citeStructure" to "citationTrees" and other minor fixes

- versions/unstable/README.md
> Made `citeType` required for `CiteStructure` objects.

- versions/unstable/README.md
> Fix examples using dictionaries as values for dublinCore
